name = 'qemantra'

[variables]
binary = "qemantra"
build-dir="build"
version="0.2.1"
main-file = "cmd/qemantra/main.go"
ldflags="-X main.VERSION='$version'"

[task.build]
description = "Build the project"
command = "go build -o $binary -ldflags \"$ldflags\" ${main-file}"
environment = [ "CGO_ENABLED=0"]

[task.tidy]
description = "Install dependencies"
command = "go mod tidy"


[task.format]
description = "Format the project"
command = "go fmt ./..."




