# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run cmd/qemantra/main.go
  format:
    cmds:
      - gofmt -w .
  build:
    cmds:
      - go build -o qemantra cmd/qemantra/main.go 
      
  test:
    cmds:
      - go test

