on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

jobs:
  build-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Build docker image
        run: |
          docker build -t pspiagicw/qemantra-docs .
      - name: Push Docker Image
        run: |
          docker push pspiagicw/qemantra-docs





