name: qemantra-check

on:
  push:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev xvfb gettext
    - name: Prepare
      run: |
        go generate
        go mod download
    - name: Verify format
      run: test `gofmt -l . | wc -l` = 0

    - name: Test
      run: |
        go test -v ./...

    - name: Build binary successuflly
      run: |
        make build
